global:
  scrape_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: spring-app
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'supersecretusername'
      password: 'supersecretpassword'
    static_configs:
      - targets:
          - host.docker.internal:8080